### ISSUE TITLE
Move enginekit fixtures to this repo.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#106]
I was initially against this idea because the fixtures are typically (always?) used by *engine* developers, not *application* developers, but everything in `fixtures` is an implementation of the interfaces in this repo, after all.

Thoughts?

**Comment by koden-km** [comment]
So you are saying its the opposite? All the fixtures are used by application developers and not engine developers.

**Comment by jmalloc** [comment]
Nah, I'm just saying I am (was) conflicted :P After sleeping on this I'm convinced they belong here.

As I split up `enginekit` in dogmatiq/enginekit#39 it, perhaps unsurprisingly, seems to be working well to put a `fixtures` package in each repo with the fixtures that specifically relate to that module.

Just for background... the stuff in `fixtures` was built for testing engines and other utility libraries. An application developer typically doesn't use them because their tests will deal with their real apps, handlers and messages.

However, everything in the `fixtures` package is an implementation of some interface in the `dogma` package, and for that reason I feel that they *do* belong in this repo moreso than anywhere else. Recall that some of the interfaces in `dogma` are provided by the engine, and others by the application.
