### ISSUE TITLE
Define and document the comparison semantics for identity names and keys.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#110]
Current engine implementations use case-sensitive (or more specifically, byte-wise) comparisons. This is probably the only sane approach; otherwise the spec needs to define case-folding and normalisation behavior which I'd rather avoid if possible. 

The spec, however, currently nominates that these identifiers must be UTF-8 strings and I'm wondering now if this is a mistake and should instead be treated as opaque byte sequences.

Either way, the recommendation about UUIDs stands, and needs to be clarified to indicate that they should be provided as lower-case, hypen-separated, hex-encoded ASCII strings (whatever this format is called), for example: `1bff04c5-3fc5-4d18-be94-313529c57b99`.

@ezzatron I would be keen to get your opinion about this at some point.

**Comment by ezzatron** [comment]
Unless these names/keys are typically taken from user input, or are displayed to users, I think the opaque byte string approach is probably fine.

If user input *is* involved, I'd probably enforce the old `/^[!-~]+$/` (all printable chars in the 7-bit ASCII range except space) pattern to keep your implementation simple.

> lower-case, hypen-separated, hex-encoded ASCII strings (whatever this format is called)

It's usually called [Kebab Case](https://wiki.c2.com/?KebabCase).
