### ISSUE TITLE
We need a way to ignore messages if an aggregate instance does not exist.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#119]
In order to properly use `Destroy()` we need to be able to ignore a message that is handled after an aggregate instance has been destroyed without recreating the instance.

At the moment the only way to tell if an instance exists is to call `Create()` and then call `Destroy()` again if it did not already exist:

```go
if s.Create() {
    s.Destroy()
    return
}

actualMessageHandlingLogic()
```

This works OK, but doesn't express intent very well and may have persistence/cache overhead in some engine implementations (though not so in `dogmatiq/infix`, FWIW).

There's quite a few different ways we could accomplish this, and I'm not yet sure if we should be trying to tackle this specific problem or simply adding a generic way to test if an instance exists. Such a feature has been omitted from the design so far to try to discourage use of existence/non-existence as a basis actual business logic.

As a side note, this decision may also make sense for processes, as `Begin()` and `End()` are direct analogues to `Create()` and `Destroy()`, respectively.

Below I list some approaches we could take by modifying the [`AggregateCommandScope`](https://github.com/dogmatiq/dogma/blob/fa49c1d233bf9c5329c9c571db42d173e9f3882a/aggregate.go#L155) interface.

1. Add an `Exists() bool` method. This is probably the simplest solution, which definitely lends it some credibility. BC break for engines.
2. Change the existing [`Root()`](https://github.com/dogmatiq/dogma/blob/fa49c1d233bf9c5329c9c571db42d173e9f3882a/aggregate.go#L192) method signature to `Root() (r AggregateRoot, exists bool)`. BC break for engines and applications.
3. Add a separate `TryRoot() (r AggregateRoot, exists)` method. BC break for engines.
4. Add a `IgnoreMessageIfNotExists()` method. This would need to panic with some value that the engine can catch. BC break for engines.

And one more approach that would involve modifying [`AggregateMessageHandler`](https://github.com/dogmatiq/dogma/blob/fa49c1d233bf9c5329c9c571db42d173e9f3882a/aggregate.go#L20)

5. Change `RouteCommandToInstance()` to allow back-holing if messages if the instance does not already exist. IIRC `jmalloc/ax` has a feature like this in its saga subsystem. BC break for both engines and applications. This approach *might* have some advantages in engines like `dogmatiq/verity` which perform routing on a separate cluster node before dispatching the message to another node for handling.

**Comment by jmalloc** [comment]
I'm currently leaning towards `Exists()` for its simplicity in understanding and ease of implementation.

`TryRoot()` would probably be mildly annoying to use because you always need to perform a type assertion on the root value, which means you need to assign to a temporary variable in order to check the `exists` boolean:

```go
if r, exists := s.TryRoot(); exists {
  x := r.(SomeType)
  logic(x)
```

contrast with:

```go
if s.Exists() {
  r := s.Root().(SomeType)
  logic(r)
}
```

**Comment by danilvpetrov** [comment]
My initial thoughts were that the boolean value returned by `Create()` is sufficient for the root existence check. However, when @jmalloc brought up simplicity of `Exists()` (even with the BC for engine implementations), I think may be we should provide that in the interface. Additionally, `Exists()` adds more readability and explicitness to the code IMHO.
