### ISSUE TITLE
Consider allowing recording an event after destroying an aggregate instance.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#132]
Doing so would essentially negate the "destroy".

**Comment by danilvpetrov** [comment]
I see you are trying to simplify even that 😄

**Comment by jmalloc** [comment]
There is a subtle potential problem with allowing `RecordEvent()` to be called after `Discard()` within the same scope. 

I wan't to try to document it because it might catch us out in the future, though I don't suspect it to be a problem in well-behaving and well-tested aggregate implementation.

The issue is that `Destroy()` has no way to "reset" the in-memory representation of an aggregate root that has already been returned by `s.Root()`. This means that it's possible that after calling `Destroy()` the root you are working on differs to what you'd see for a fresh aggregate instance.

The reason I say this *shouldn't* be a problem is that:

- Calling `Destroy()` still requires you to have recorded at least one event in the current scope. In a **well-behaving** aggregate, the implementation of `AggregateRoot.ApplyEvent()` will return the root to its "initial state" based on these "destroy events".
- Even  if `ApplyEvent()` doesn't return the root to an *identical* state as a new instance, a **well-tested** aggregate will quickly identify whether the differences in state actually matter to the business logic or not. The next time the instance receives a command the instance will be "reconstituted" from only those events that occurred after the destruction.

**Comment by jmalloc** [comment]
I think I can make that whole "problem" go away, if we state specifically that `RecordEvent()` after a `Destroy()` actually "undoes" the request to destroy, making it equivalent to if `Destroy()` had never been called.  

This is as opposed to describing it such that the aggregate instance is destroyed, and then re-created when `RecordEvent()` is called.
