### ISSUE TITLE
Rename `AggregateCommandScope.Destroy()` to something more appropriate.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#136]
`Destroy()` is a very direct and "harsh" name compared to the actual documented behavior of the method, especially considering the actual behavior is engine-defined.

The one guarantee is that after calling `Destroy()`, and so long as you don't subsequently record a new event, the *next* command message will see a new "empty" aggregate root value as returned by `AggregateCommandHandler.New()`.

Here's a few suggestions that have come up:

- `Dispose()`
- `Discard()`
- `Forget()`

**Comment by koden-km** [comment]
So far I think I like `Dispose()` and `Discard()`.

I think i'm leaning 49% toward `Dispose()` and 51% toward `Discard()`

**Comment by jmalloc** [comment]
After discussing on Slack, we're going to leave this alone for now.
