### ISSUE TITLE
Review process message handler API.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#138]
In light of recent changes to the aggregate API, I'd like to revisit the equivalent process interfaces to see if we can improve consistency between the two, and perhaps decrease the complexity of `Process[Event|Timeout]Scope` in particular.

To recap the changes to aggregates:

1. `AggregateCommandScope.Create()` has been removed
2. `AggregateCommandScope.Exists()` has been removed
3. `AggregateCommandScope.Destroy()` and `RecordEvent()` can be called in any order
4. The root is passed to `HandleCommand()` and `Root()` has been removed

I am not certain that we can make an equivalent change to processes for all of these. One reason is that processes have no equivalent of `ApplyEvent()` because they are not required to produce message in order to change state.

It's easy to see why this is necessary if you imagine a process that occurs whenever two specific events occur, and those events can occur in either order. To implement such a process you need to keep knowledge of whichever event occurs first without executing any command until the second event occurs.

Below I will attempt to discuss the aggregate changes above as they might be applied to processes. 

## 1. Remove `ProcessEventScope.Begin()`

Because processes are not required to produce a message to signal a state change, `Begin()` currently serves to instruct the engine that we care about this process instance and want to start persisting its state. Don't confuse this for an equivalent to "begin a database transaction", it means "begin the business process".

In order to remove this method, we need some way to ignore events that *could* potentially start the process because they are the right type, but *don't* start the process because of the data within them. One example of this, which I believe does actually occur in `dogmatiq/example`, is that we begin a `DepositProcess` when we receive a `TransactionStarted` event, only if the transaction type within the event is `DEPOSIT`.

Such messages can usually be ignored at the routing stage by returning `false` from `RouteEventToInstance()`. However, some process implementations may need to query some read-model to work out that the event should be ignored.

Without `Begin()` to indicate "this event is actually starting the process", we might need some inverse to say "this event *isn't* starting the process". Perhaps that could be in the form of the existing `End()` method?

I wonder, with this approach, if you might easily end up with several process instances that were never meant to be started, simply because you forgot to call `End()` &dagger;.

## 2. Remove `ProcessEventScope.HasBegun()`

This was added as an analogue to `AggregateCommandScope.Exists()`. If we manage to remove `Begin()` I don't think it will be necessary anymore. You can kind of think of these changes as making the lifetime management "automatic".

## 3. Remove call-order dependencies between `End()`, `ExecuteCommand()` and `ScheduleTimeout()`

I think we could make this work the same as aggregates fairly easily. Any call to `End()` would be "negated" or "undone" by a subsequent call to `ExecuteCommand()` or `ScheduleTimeout()`.

There is currently no requirement that you execute a command in order to call `End()`. Any scheduled timeouts are canceled when `End()` is called.

## 4. Pass `ProcessRoot` directly to `Handle[Event|Timeout]()`

So long as we remove `Begin()` I think this change would be fine too. If we were to make this change *and* retain `Begin()` it would be easy for someone to modify the root value that is passed to the handler but have those changes ignored because they forget to call `Begin()`. The requirement that `Begin()` be called before you are allowed to call `Root()` is what currently protects the user from this problem.

Remember that `ProcessRoot` is an empty "marker" interface, we can't easily detect a change to a root without requiring the application to implement some kind of cloning, comparison or hashing operations on the roots, and so far I have been very reluctant to make this a requirement. It would likely be annoying and difficult to implement, and potentially also engine specific.

---

&dagger; I think that all of the problems raised with each of these changes is likely to be caught by testing in a well-tested application, except this one. I also don't want to make an API that's difficult to use properly and just have-wave away the problems by saying "you should test more".

**Comment by jmalloc** [comment]
Under section (1) in my main comment I say:

> Such messages can usually be ignored at the routing stage by returning `false` from `RouteEventToInstance()`. However, some process implementations may need to query some read-model to work out that the event should be ignored.

I've been thinking on this point some more, and I'm not sure there's any particular reason a process couldn't query a read-model within `RouteEventToInstance()`. If we made that the norm we could probably remove `ProcessEventScope.Begin()`, but I'm not sure that actually makes for a better experience.

**Comment by danilvpetrov** [comment]
IMHO All points make sense, except for the first one `Remove ProcessEventScope.Begin()`. In my view the nature of the processes require them to start inflating the state only after certain commands are consumed and we should leave it up to the user to decide what are those commands. Some processes are more complex than others and might expect the commands come in various orders. To me processes can be used in various scenarios where it's only up to the user to decide what are those state-inflating commands.

**Comment by jmalloc** [comment]
What do you mean by "inflating the state" in this context?

Remember also that processes handle events, not commands. I'm not sure if that changes your opinion in any way, but just a reminder :)

**Comment by danilvpetrov** [comment]
Sorry, I definitely meant the events for the processes. It wouldn't change my opinion though :). At least for now. I *think* that we would still need `ProcessEventScope..Begin()` to let the engine know that we do want to persist the state of the process from now on.

**Comment by jmalloc** [comment]
I will need time to think this through more deeply, but I think retaining `Begin()` would also necessitate retaining `HasBegun()` unless the semantics of `Begin()` and `End()` were to be changed.

**Comment by jmalloc** [comment]
After discussions on Slack and in person we've decided to try the following changes, which aligns with the original proposals:

- Remove `Begin()`, `Root()` and `HasBegun()`
- Do not panic from `End()` if `End()` has already been called
- Pass the `ProcessRoot` directly to `HandleEvent()` and `HandleTimeout()` methods
- "Negate" a prior call to `End()` if `ExecuteCommand()` or `ScheduleTimeout()` is called

**Comment by jmalloc** [comment]
As per ADR-19:

- [ ] Remove `ProcessEventScope.Begin()`.
- [ ] Remove `Process[Event|Timeout]Scope.HasBegun()`.
- [ ] Remove `Process[Event|Timeout]Scope.Root()`.
- [ ] Pass the process root directly to `ProcessMessageHandler.Handle[Event|Timeout]()`.
- [ ] Allow `Process[EventTimeout]Scope.End()` to be called at any time.
- [ ] Allow `Process[EventTimeout]Scope.ExecuteCommand()` and `ScheduleTimeout()` to
  be called at any time. Doing so should "negate" any prior call to `End()` as
  though it were never called.
- [x] Remove `StatelessProcessRoot` and `StatelessProcessBehavior`. With the
  notion of "existence" being removed from the public API a stateless process
  becomes nonsensical.
- [ ] Routing a command message to a process instance causes that instance to begin.

**Comment by jmalloc** [comment]
> * Remove `StatelessProcessRoot` and `StatelessProcessBehavior`. With the
>   notion of "existence" being removed from the public API a stateless process
>   becomes nonsensical.

I'm actually not sure if stateless processes *are* nonsensical. I could imagine a situtation where an entire process is unconditionally executing some command based on some event.

Thoughts?

**Comment by koden-km** [comment]
> I could imagine a situtation where an entire process is unconditionally executing some command based on some event.

Yeah that seems like something that would be handy.

**Comment by danilvpetrov** [comment]
I guess a good example of stateless processes could be  integration processes with some legacy systems.

**Comment by jmalloc** [comment]
Ok, I'm thinking I should remove that decision from the ADR then, do you guys agree?
