### ISSUE TITLE
Add the "banking" example.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#16]
It would be fantastic if we could do this in such a way that it ran the under in-memory test engine (#15) and implemented a simple API, or even a very basic web front-end, so that we could see the example work without requiring a more substantial backend.

**Comment by jmalloc** [comment]
It should definitely have tests written using Dogma's testing tools.  If we decide (via #17) to move the testing tools to a separate module, then the example would likely need to move to a separate module as well, otherwise we will introduce a circular dependency.

I feel this is another argument to keep the testing tools in the same module.

**Comment by danilvpetrov** [comment]
It feels ok to me to move both testing tool and example into separate module. It's seems to be standard for many golang libraries to combine tests and examples in the same module.
