### ISSUE TITLE
Choose a software license.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#20]
Everything I've released on GitHub in the past has been done under an MIT license. I don't see any particular reason to change that, but I thought I'd throw it out there.

There's a bunch listed [here](https://opensource.org/licenses), there's also the Creative Commons [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) "no rights reserved" license and the [Unlicense](http://unlicense.org/).

**Comment by danilvpetrov** [comment]
I don't see the reason to change licence type either. I am ok with MIT.
