### ISSUE TITLE
Change routing documentation regarding "zero" values.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#30]
In the `AggregateMessageHandler.RouteCommand()` and `ProcessMessageHandler.RouteEvent()` methods, the documentation mentions that when a routing probe is being performed that the message will be a zero-value.

I think this needs to be relaxed to state simply that the content of the message is undefined, for a few reasons:

- There's no real reason it *has* to be a zero-value, since the documentation is instructing the implementor to only use the message's type, not its value.
- Attempting to enforce zero-values in the engine implementation requires a bunch of unnecessary reflection.
- How do we deal with pointer values, do we really want to require that the engine pass a nil pointer to a message if the message implementation uses pointer receivers? What if it's not a struct at all?

/cc @danilvpetrov @koden-km thoughts?

**Comment by danilvpetrov** [comment]
I totally agree with first two bullet points. In regards to the third one: can’t there be so go reflection code to determine if it’s a pointer or not and determine the type accordingly? Restricting a message to be a struct  might be adequate, I agree with this point as well.

**Comment by jmalloc** [comment]
We *could* do something like that with reflection, but to be clear, I definitely don't want to restrict messages to be implemented as structs. In trying to keep everything as "normal Go" as possible, all that should matter is that messages implement `Message` (which is empty at the moment).

In order to help achieve this, I think we need to avoid mandating what values the engine passes in this case. By saying it has to be a zero-value, we have to be able to *check* that things are zero-values and/or produce them in the engine. This opens the question as to whether that will make much sense, or match the expectation of application developers.

If we instead simply say: when `Route<Whatever>()` is called with the `probe` flag set to true, `m` is guaranteed to be a non-nil message, the contents of which is undefined, we don't place unnecessary requirements on the engine implementation.

This question came about when I was playing around with some ideas for an in-memory engine last night. The application needs to register the available message types somehow. To keep things simple I wanted it to look something like this:

```go
var bankDomain = Domain{
	Commands: []dogma.Message{
		&messages.OpenAccount{},
		&messages.Deposit{},
		&messages.CreditAccountForDeposit{},
		&messages.Transfer{},
		&messages.CreditAccountForTransfer{},
		&messages.DebitAccountForTransfer{},
		&messages.Withdraw{},
		&messages.DebitAccountForWithdrawal{},
	},
	Events: []dogma.Message{
		&messages.AccountOpened{},
		&messages.DepositStarted{},
		&messages.AccountCreditedForDeposit{},
		&messages.TransferStarted{},
		&messages.AccountCreditedForTransfer{},
		&messages.AccountDebitedForTransfer{},
		&messages.TransferDeclined{},
		&messages.WithdrawalStarted{},
		&messages.AccountDebitedForWithdrawal{},
		&messages.WithdrawalDeclined{},
	},
	Aggregates: []dogma.AggregateMessageHandler{
		bank.AccountHandler,
		bank.TransactionHandler,
	},
	Processes: []dogma.ProcessMessageHandler{
		bank.DepositProcessHandler,
		bank.WithdrawalProcessHandler,
		bank.TransferProcessHandler,
	},
}
```

Then I thought this worked nicely, because I could pass these "zero-value" messages during the routing probe, but I wanted to validate that they were zero values first. Which is when I realised that they aren't! Because the zero-value would be a nil pointer, not the pointer-to-empty-struct I have here!

Anyway, all of this just spammy background as to why I think the documentation language should be relaxed. If we treat this like a specification I would consider the current language to be over-specified.

**Comment by koden-km** [comment]
I'm not familiar enough with Go regarding this. Do you want `nil`, and does that still know its type, or is that lost as it becomes a generic `nil` pointer to a `Message` interface?

What if a real message gets sent during a probe? I suppose that's fine to ignore the content and just probe it as asked.

**Comment by jmalloc** [comment]
Importantly, there is a distinction between a `nil` interface value, and an interface variable that contains a value that is `nil`. I think you get that, but just to illustrate it: https://play.golang.org/p/fTVvB7-VSDR

I want to make it so that the only guarantee the engine must provide is that `m` is a non-nil interface value. In the code I linked, the first call to `fn()` does NOT honour this guarantee, but the second does.

> What if a real message gets sent during a probe? I suppose that's fine to ignore the content and just probe it as asked.

Yep, basically, if `p` is true, the contents of the message is to be ignored.

**Comment by danilvpetrov** [comment]
Yep, that's all makes perfect sense: nil interface value absolutely prevents from getting any variable type information.

**Comment by jmalloc** [comment]
Also see https://golang.org/doc/faq#nil_error

**Comment by koden-km** [comment]
I like the `bankDomain` definition example you provided.

**Comment by jmalloc** [comment]
Cool, so I doubt there's any reason NOT to make this doco/spec change at this point, yeah?

**Comment by jmalloc** [comment]
I think I'm finally ready to relent and split the `RouteXXX()` methods in two like Kev has been saying all along, like so:

```go
type AggregateMessageHandler interface {
    // returns empty messages for all types that should be routed here
    AcceptedCommands() []dogma.Message

    // does what RouteCommand did in non-probe mode
    SelectTargetInstance(m dogma.Message) (string, bool)
}

type ProcessMessageHandler interface {
    AcceptedEvents() []dogma.Message
    SelectTargetInstance(ctx context.Context, m dogma.Message) (string, bool, error)
}
```

It's the process one, especially, that is convincing me -- because it doesn't make sense to accept a context and allow an error return when routing, the signatures really are different.

**Comment by jmalloc** [comment]
I'm going to close this, since #32 is merged.
