### ISSUE TITLE
Create an embeddable type that implements HandleTimeout().

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#39]
It should always panic with the `UnexpectedMessage` value.

I'm not sure what it should be named, perhaps something like `NoTimeouts` or `NoTimeoutSupport`?

**Comment by koden-km** [comment]
Maybe just the short name `NoTimeouts`, unless you think there will be a few helpers and you want to make them follow a pattern like `NoXxxSupport`/`HasXxxSupport`?
