### ISSUE TITLE
Review all naming before release.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#43]
Blocked by #11 - as that may introduce some more code to 1.0.0.

**Comment by jmalloc** [comment]
Here's what we have so far, condensed without documentation for an easy overview. I'll update this to include anything we add for #11:

# Aggregate

```go
type AggregateMessageHandler interface {
	New() AggregateRoot
	Configure(c AggregateConfigurer)
	RouteCommandToInstance(m Message) string
	HandleCommand(s AggregateCommandScope, m Message)
}
```

```go
type AggregateRoot interface {
	ApplyEvent(m Message)
}
```

```go
type AggregateConfigurer interface {
	RouteCommandType(m Message)
}
```

```go
type AggregateCommandScope interface {
	InstanceID() string
	Create() bool
	Destroy()
	Root() AggregateRoot
	RecordEvent(m Message)
	Log(f string, v ...interface{})
}
```

```go
type DomainCommandExecutor interface {
	ExecuteCommand(ctx context.Context, m Message) error
}
```

```go
type StatelessAggregate struct{}

func (StatelessAggregate) New() AggregateRoot {
	return StatelessAggregateRoot
}
```

```go
var StatelessAggregateRoot AggregateRoot = statelessAggregateRoot{}

type statelessAggregateRoot struct{}

func (statelessAggregateRoot) ApplyEvent(m Message) {
	if m == nil {
		panic("event must not be nil")
	}
}
```

**Comment by danilvpetrov** [comment]
Following the first bullet point: would it be useful to call them `sets`? Go has a notion of method sets that can be attached to any type. At the same time it may not be appropriate as method sets are commonly mentioned with the type of receivers (pointer vs value).

**Comment by danilvpetrov** [comment]
Second bullet point: as I understand we are talking about a domain command, right? In this case I do support the idea that it should not be routed directly to integration handlers. As it was mentioned, probably the interface should not anyhow restrict it, but its documentation can always refer to the matrix for the implementation guidance to remind about restrictions.

Third bullet point:  I am all for the base interfaces such as `Logger`, `Executer`, etc. and combine them in the specific interface to lego-built its functionality.

**Comment by koden-km** [comment]
1. I haven't done as much Go as you guys, but for naming of 'embeddable types' i think i prefer "behaviour" over "trait". It seems to read a bit more like English. `NoTimeoutBehavior`, `StatelessAggregateBehavior`.

1. I'm not sure i understand this one. I thought the user always submits commands to get things done?

1. I don't think there is too much duplication here. Overall it's currently a fairly small API and keeping it all right there in each interface definition could make it easier to follow for implementing. You guys know the language better than me about embedding those.

**Comment by jmalloc** [comment]
> The mental overhead of keeping docs in sync when making changes?

Yeah

**Comment by jmalloc** [comment]
I think the only things here I'm still especially bothered by are:

- `DomainCommandExecutor`
- `IntegrationEventRecorder`

I'm not confident about the distinctions we make about domain/integration messages.  I think those distinctions should largely be recommendations, not strict requirements, and as such we shouldn't preclude an engine from accepting an integration command or a domain event from "outside".  With that in mind, maybe these should just be named:

- `CommandExecutor`
- `EventRecorder`

**Comment by koden-km** [comment]
Isn't there already an `EventRecorder` that aggregates use?

**Comment by jmalloc** [comment]
There's a `RecordEvent()` method on `AggregateCommandScope`, but these interfaces are for "putting messages in from the outside".
