### ISSUE TITLE
Add Create and Destroy methods to AggregateScope.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#5]
As per #1, we decided that such methods are necessary, as otherwise there would be no way to manage the lifetime of CRUD aggregates (as opposed to those running on an ES engine).

Were we happy with the names `Create()` and `Destroy()`?  The equivalent methods for a workflow are named `Begin()` and `End()`.

I feel that `Destroy` is marginally more applicable to both CRUD and ES implementations, whereas `Delete` does imply more forcefully to me that the data would be removed, which is not true under ES.  I think `Create` is fine in any scenario.

We might also consider naming the `Begin`/`End` just like workflows. Any thoughts?

/cc @danilvpetrov @koden-km

**Comment by jmalloc** [comment]
I'll start an ADR for this once #4 is established.

**Comment by koden-km** [comment]
Is there much benefit in keeping the method names the same between aggregates and workflows? I'm ok with `Create`/`Destroy`, but `Begin`/`End` could work also. I guess i need to see a few examples to get a feel of it. Are these the new version of the old Dogma workflow `WorkflowScope :: BeginWorkflow()`?

**Comment by jmalloc** [comment]
There’s probably not much benefit in them being the same, no. We should try to capture the intent of controlling the lifetime of the aggregate, remembering that it could mean any number of different approaches taken in the persistence label. 

And yeah, the methods I was referring to on `WorkflowScope` In the old repo were called `BeginWorkflow`/`EndWorkflow`. I named them so explicitly because otherwise it read as though you are beginning/ending the scope itself. We may want to consider such ambiguity here, too.

**Comment by jmalloc** [comment]
It also occurs to me that name `Create` might suggest that it could be called many times within the same scope, to create many instances, which is not the case. The names begin/end do not seem to have the same connotation to my ears. This is not an argument for or against any particular choice.

**Comment by jmalloc** [comment]
I'm attempting to write the docs for this now, and `Destroy()` is proving difficult because so much of the behaviour is defined by the engine.  

I'm trying to distill down exactly what calling the method is really saying, from the domain perspective, and I think it's something more like "lock" or "become immutable" -- "there is no more business logic to be done here".

**Comment by jmalloc** [comment]
Maybe something like `Done()` is more appropriate, as it doesn't imply any particular kind of behavior, at least to my ears.

**Comment by jmalloc** [comment]
Hrm, I changed my mind about that again (see #7).  I opted to retain `Destroy()` because while it doesn't necessarily mean the *events* are being deleted, it does still need to imply that the aggregate state is destroyed.

To put it another way: in an ES implementation, calling `Destroy()` would still need to cause future commands to see a "new" instance.

**Comment by jmalloc** [comment]
To be clear, I'm trying to get at an approach that actually works the same (from the domain layer's perspective) for CRUD and ES, and I think in that case the names Create/Destroy are actually OK.
