### ISSUE TITLE
Specify some basic requirements on the format of handler and app names.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#53]
The engine implementation may place its own requirements on the structure of names, but I think we should place some basic requirements in the dogma "spec" itself, something fairly basic like

- no whitespace 
- non-empty

I don't want to preclude using UTF-8 names or anything like that, but this at least sets a baseline for interoperability.

**Comment by jmalloc** [comment]
If anyone can think of any other specs that might layout some good requirements for similar kinds of identifiers, please lmk.

**Comment by koden-km** [comment]
That sounds good so far. I can't think of anything else at this stage.

**Comment by jmalloc** [comment]
I'm looking for some definition inside unicode where we could say something like "names must consist solely of printable unicode characters" or something like that

**Comment by jmalloc** [comment]
Check out https://golang.org/pkg/unicode/#pkg-variables -- the `PrintRanges` variable specifically.

**Comment by jmalloc** [comment]
@danilvpetrov do you have any thoughts or concerns about this?

**Comment by danilvpetrov** [comment]
No questions, all seems to be clear, thanks!

**Comment by jmalloc** [comment]
Ok, so in terms of spec language for this, how does this  sit:

```
Name MUST be a non-empty UTF-8 strings consisting solely of printable unicode characters.
A printable character is any character from the Letter, Mark, Number, Punctuation or Symbol categories.
```
