### ISSUE TITLE
Clarify semantics around creating/destroying aggregate and process instances within the same message.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#55]
TL;DR It should be allowed to create then destroy within one message, but not destroy then create.

This will simplify engine implementations, and doesn't lose us anything (why destroy then create, just don't destroy in the first place).

**Comment by jmalloc** [comment]
See #116 for further context.

**Comment by jmalloc** [comment]
Accidentally pushed this straight to `master` in 139665b.

@koden-km, @danilvpetrov would appreciate a quick eyeball of the language changes in that commit.

**Comment by koden-km** [comment]
I think this should be `Begin()` not `Create()`?
https://github.com/dogmatiq/dogma/commit/139665bcd5dd36c932c30198c44479f70e498660#diff-837cc8a2afa55dfd32c6ff6d135feb979c715f582a4ee3b6250288e747f84463R238

**Comment by koden-km** [comment]
^ also same thing for the other one in that file:
https://github.com/dogmatiq/dogma/commit/139665bcd5dd36c932c30198c44479f70e498660#diff-837cc8a2afa55dfd32c6ff6d135feb979c715f582a4ee3b6250288e747f84463R299

**Comment by jmalloc** [comment]
Right you are. Lucky I have you guys.

**Comment by jmalloc** [comment]
Fixed.
