### ISSUE TITLE
Consider requiring `Configure()` to specify the produced messages.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#71]
The `Configure()` method on all handler types must currently specify the message types that are to be routed to that handler. This is a necessity for implementing any engine.

This issue proposes adding the requirement that `Configure()` implementations also specify the types of messages that the handler will produce. That is, the types of events that may be recorded by an aggregate or integration handler, or the types of commands executed by a process handler.  Timeout messages should probably not be included in this requirement, as they are "private" to a specific process, and not routed between handlers.

While having this information is not a necessity for any engine implementation, it does provide valuable information such as a definitive list of the events that are produced. This information has a few potential use-cases, such as building message routing tables for inter-app communication, or to enforce requirements that a given events are only produced by a single aggregate.

If we were to add these methods to the interface, my current stance is that it should be mandatory to advertise the produced messages. That means that if any handler were to produce a message of a type that had not been specified in `Configure()`, the engine should (or perhaps must) treat this as a logic error.

My main concern about whether to implement this at all, is that it appears to be the first time we'd be adding a feature that does not directly serve interoperability, although perhaps the argument could be made that having this information and not using it (in a given engine implementation) opens more doors than not having it at all.

**Comment by danilvpetrov** [comment]
This is undoubtedly useful feature, IMHO it needs to be implemented. My only concern is how clunky would application layer get if it needs specify produced messages by the entities. At the same time we probably would not expect an entity to produce a large number of messages, so it might not be that bad.

I am leaning towards having this implemented as it can facilitate the creation of other features involving visualisation of message flows in the apps, etc.

**Comment by koden-km** [comment]
I like the idea. Its good to know up front what exists when starting work on an existing project and also for integrating with one.

One thing i'm not sure about is "events are only produced by a single aggregate". Is that really always the case? It seems ok for really specific things, but an event is an event, does it matter where it came from?

**Comment by jmalloc** [comment]
It matters, because if it comes from two places, that means you have two separate pieces of business logic that "do the same thing".

**Comment by jmalloc** [comment]
I will add that such a restriction could be engine defined - it doesn't necessarily have to be written into the spec.

**Comment by koden-km** [comment]
Yeah that's fine. I was just curious with the event thing because you said a command could be injected to "fix" an issue, I was wondering if something similar made sense for events.
What would happen for an injected command in that situation? It couldn't have been injected because then it didn't come from an aggregate?
