### ISSUE TITLE
Consider adding a Time() method to ProcessTimeoutScope

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#78]
I think it's pretty reasonable to want to know the time that a timeout is scheduled to occur. However, this hasn't been done yet as the argument is that the message itself should contain the time if it is relevant to the domain. This is certainly true for commands and events, but I wonder if this is just an annoyance for timeouts, which are essentially an implementation detail of the process they belong to.

**Comment by jmalloc** [comment]
I don't see any reason not to include this feature. Like all of these small changes it does grow the API a little, but I think the benefits are justified and if we're going to add it I'd rather see it included earlier.

@danilvpetrov Do you have any thoughts, especially given you've been using Ax's equivalent "delayed command" features?

**Comment by danilvpetrov** [comment]
It seems really reasonable to have this method. It could be used for calculating the next command execution, etc. 

In case the message represents the event what would be the value returned by this method then? Would it return time.Now() to signify the earliest possible sending? I might be asking stupid questions here, sorry in advance. 😄

**Comment by jmalloc** [comment]
Haha, this would only apply to timeout messages anyway, as it'd be on the `ProcessTimeoutScope` interface!

It's a question as to whether the Dogma API should make the original scheduled time available via the scope, or if the application developer should be required to include the scheduled time inside their timeout messages if that information is required. I feel this is actually a difficult decision to make, and I'll try to give some background as to why.
 
Some time ago, we had a discussion about adding a similar method to event scopes. In the end we made a decision (without an ADR 😱, my bad) to add a `Time()` method to `ProjectionEventScope` but **not** to `ProcessEventScope`. 

The rationale here is that it's reasonable for a projection to care about the time at which arbitrary events occur simply to represent that information in a read-model, even if the domain logic itself has nothing to do with time.

Processes, on the other hand, should base any time-centric decisions on the content of the events themselves, not the time they happened to be recorded in the database. Thus we've been saying they "model time" within the events.

Now, back to timeout messages. The moment your application uses timeout messages, by definition it has some time-based logic. If you recall, the two examples we keep throwing around are some kind of recurring transfer in the banking example, or the marking of an invoice as overdue in some hypothetical billing system.

If we do add a `Time()` method to `ProcessTimeoutScope`, we are inconsistent with our assertions that domain logic that cares about time should "model time" within messages explicitly. 

That being said, timeout messages are always routed back to the process instance that scheduled them. This makes them a kind of implementation detail of that specific process. In which case, does it really make sense to require the developer to add an additional "scheduled-at" field to their timeout messages just to convey information that the engine already has available.

I apologise for the wall of text. This issue has been bugging me for a while but I'm probably being overly academic about it. I'm currently leaning towards just adding the method as a matter of convenience.

**Comment by danilvpetrov** [comment]
All right, after what I read, I now see that I had _ax/hive_ tunnel vision  when wrote the previous comments. 

Thanks for the extensive explanation of the issue. After all of that I am inclined to say that this method is redundant as will set the delay in the processes anyway. I feel like this method is a bit excessive now.

**Comment by jmalloc** [comment]
Thinking about this further, there are valid use-cases where a process may want to know when an event occurs, even if the domain does not have a time component.

For example, we talk about the idea of triggering a "promotion process" off a custom sign-up event, something like "give everyone who signs up before <some date> a $5 bonus".  So, time is an element in the *process*, but not in the original "sign-up" event.  

My current position is that this argues in favour of adding a `Time()` method to `ProcessEventScope` as well - further weakening the argument for omitting such a method from `ProcessTimeoutScope`.

**Comment by danilvpetrov** [comment]
So this `Time()` method would return scheduled time for command messages and recorded time for event message, right?

**Comment by jmalloc** [comment]
Yeah, that's right.

**Comment by koden-km** [comment]
It sounds like time should be part of the event in that case? You can't just assume some time later on?

**Comment by jmalloc** [comment]
So, after discussing with both you guys individually, I *think* we agree that we should add `Time()` methods to all `XXXEventScope` and `ProcessEventScope` interfaces.
