### ISSUE TITLE
Add a feature for specifying "first run" commands.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#83]
The intent is to execute a set of commands once-only when an application is first deployed.
One example use case is to start a process that executes indefinitely.

**Comment by jmalloc** [comment]
Possible approaches:

- Add a method to `ApplicationConfigurer` that allows enqueueing "first-run" commands for execution.
- Add a method to `Application` that returns the set of commands.
- Add a more general hook method to `Application` that can do whatever is appropriate on the "first-run", including schedule commands.

**Comment by jmalloc** [comment]
@ezzatron I wonder if you might have any opinions about this with your recent work on Recluse.

**Comment by ezzatron** [comment]
I haven't really got this far with Recluse yet, but I'll try to remember to come back once I have an opinion.

**Comment by jmalloc** [comment]
FWIW, we're currently leaning towards option 4:

> 4. Implement some standard integration events in Dogma itself, such as an `ApplicationDeployed` event.

**Comment by jmalloc** [comment]
@danilvpetrov Did a need for this feature arise in Hive 2?

**Comment by danilvpetrov** [comment]
This is potentially a very useful feature to start some sub-services. We can potentially start certificate renewal service using this type of commands, etc. I would definitely like to have this feature in Hive2.

**Comment by jmalloc** [comment]
I'm not sure if we're using the same terminology, but I don't think it could be use to start a "service" (which would need to run whenever the server started, not just when the application was first deployed?).  It could however be used to start a Dogma process - I don't recall if the cert renewal stuff in Hive 2 was implemented as a process or just a simple sleeping/polling goroutine though.

I'm trying to recall where this issue originated. It may have even been discussions with @ezzatron or from the Dogma example project.

**Comment by ezzatron** [comment]
I think it came from needing schema creation tasks to run.

**Comment by danilvpetrov** [comment]
Ok, I definitely misunderstood them then. So, essentially, this commands will be replacements for what Hive2 is doing atm with service hooks, right?

**Comment by jmalloc** [comment]
Nah, I'm not convinced that is correct either.  The original requirement would have had to have been some seeding of aggregate state, or kicking off Dogma processes that ran "forever".

**Comment by ezzatron** [comment]
Pretty sure the discussion surrounding this came out of my copy of the banking example app over in Recluse. I mentioned that I had an [initialize](https://github.com/ezzatron/recluse/pull/8/files#diff-5521b646749e9a89e6e578a3b39538fc) option in my application "spec" that the app could use to create its schema.

Then a little while later you made this issue. But that doesn't necessarily mean that this issue was specifically about that. We were just discussing that stuff at the same time.

**Comment by jmalloc** [comment]
So rereading this with all we've learned and changed, I still think option 4 above is the way to go 

> 4. Implement some standard integration events in Dogma itself, such as an ApplicationDeployed event.

I don't think "deployed" is the right word, but it's kind of like a "seeding" as Erin mentioned above. It would happen at the time an engine boots up and discovers an empty "data store" for the first time, be that a real database, or a new empty in-memory engine, or whatever. Then name should use Dogma terminology, not anything to do with "databases", however.

**Comment by jmalloc** [comment]
To clarify, the reason that I don't think "deployed" is the right word is because it kind of sounds like it would fire every time you deploy a new version. Likewise, `ApplicationStarted` sounds like it'd fire every time an engine instance starts.

Another option, I suppose, is that we *don't* make this feature part of Dogma at all, but rather just have engine-specific ways to fire off events once-only when an application is first spun up by an engine.

**Comment by ezzatron** [comment]
There is some prior art in Redux, which always fires an action with a type of `@@INIT` as the very first action. In Redux, this is used to run every reducer with an action that none of them should be listening to, so that they get a chance to return their "initial" state.

Not exactly the same concept, but there are some parallels.

**Comment by jmalloc** [comment]
I'm closing this as it's something to be solved using a `dogma.CommandExecutor()` and domain-level idempotency checks.
