### ISSUE TITLE
Consider allowing handlers to specify their own timeouts / deadlines.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/dogma#84]
This discussion came up because the inter-replica messaging implementation in [verity](https://github.com/dogmatiq/verity) needs to invoke a gRPC API that in turn invokes a specific Dogma handler.

I was discussing with @koden-km what value the client-side of that gRPC API should use, and we came to the conclusion that the best result would be for the client-side to know what timeout the server-side will be using to compute its deadline, and to configure its own deadline to be slightly later.

For this reason, it's not adequate to allow the handler methods to simply setup their own deadline via a context, as there's no way for the client-side to query that before making the RPC request.

What we're proposing is adding a `ComputeHandleTimeout(dogma.Message) timeout.Duration` method to all handlers except aggregates. Aggregates do not use a context/timeout as their handle-methods are in-memory, deterministic operations. 

If `ComputeHandleTimeout()` returns `0`, the engine must apply some default timeout. We can provide a "behavior" struct that returns `0` unconditionally.

The name of this method is definitely still up for discussion. It needs to be named in such a way that its clear that it relates to the calculation of deadlines, as opposed to being anything specifically to do with "timeout messages" that a process schedules.

**Comment by jmalloc** [comment]
@koden-km, @danilvpetrov I'd appreciate any suggestions as to how to name this method.

As a matter of record for the future ADR, we decided that it is most appropriate to include such a method in the Dogma API specification, as that means it lives alongside that code that is subject to that timeout.

Kev, keep in mind that in Go terminology, a "deadline" refers to a specific wall-clock time, whereas "timeout" refers to a duration used to compute that deadline, based on the current time.

**Comment by koden-km** [comment]
So by that reasoning it could be called `ComputeHandleDuration()`?

**Comment by jmalloc** [comment]
It could, I’m just not particular fond of the `Compute` prefix - we don’t put that in front of any other method that computes stuff. Also, in actuality it would most likely return a constant or a value from an environment variable, and hence not *compute* anything at all.

**Comment by koden-km** [comment]
So more like a `TimeoutDuration(message)`?

**Comment by jmalloc** [comment]
Yeah. Do you guys feel that's unambiguous enough alongside the concept of "process timeout messages", specifically when the handler will have a `HandleTimeout()` method alongside this new one?

**Comment by jmalloc** [comment]
See https://github.com/dogmatiq/dogma/blob/master/process.go#L96

**Comment by koden-km** [comment]
They still seem a bit too similar to me.

**Comment by jmalloc** [comment]
Some suggestions:

- `MaxHandlingDuration(dogma.Message) time.Duration`
- `MaxDuration`
- `HandlingTimeout` (still pretty close to `HandleTimeout(m)`
- `ExecutionTimeout` (execution is terminology usually only used for commands)

I do feel like it should have the word `Timeout` in its name, just to be inline with standard Go terminology.

**Comment by jmalloc** [comment]
I'd like to make a call on this so I can include it in the next tag.

**Comment by jmalloc** [comment]
To throw another option out there, what about `TimeoutForMessage(dogma.Message) time.Duration`.

**Comment by danilvpetrov** [comment]
IMHO, that sounds a bit closer to what we are trying to find here.

**Comment by koden-km** [comment]
Yeah that might be clear enough.

What about `DurationForMessage(dogma.Message) time.Duration`. Or do you specifically want to have "timeout" mentioned in it?

**Comment by jmalloc** [comment]
I think it is best to include the word `Timeout`.  Even though that term is overloaded within Dogma, it's still the standard Go / networking terminology. The duration will be used somewhat like this, most likely:

```go
d := handler.TimeoutForMessage(msg)
ctx, cancel := context.WithTimeout(ctx, d)
// ...
````

**Comment by jmalloc** [comment]
This was completed in #88 / be61a90b283d3b128b112a858bdc980d9ed7bab7.
